### ISSUE TITLE
Registering with same username twice!!!

### ISSUE THREAD

**Issue by afridi26** [duo-labs/webauthn.io#15]
Hi,  While playing around with webauthn.io I tried to register the same user twice and even three times? and more. What I believe for the same username the library must send excludeCredentials that tells the authenticator that for the public keys already existing for a given use and it is provided by the relying party's server if it wants to prevent the creation of new credentials for an existing user.
 [Link for excludeCredentials field](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/excludeCredentials)
![Screenshot from 2019-07-18 13-53-02](https://user-images.githubusercontent.com/5488091/61463765-627ae600-a975-11e9-92ed-2c78e0d6b67f.png)

**Comment by aseigler** [comment]
I had to look because I know I had specifically addressed this, but yes, it is definitely an issue in current master branch.  This is fixed in server.RequestNewCredential() in the fido-testing branch as this scenario is tested by the conformance test tool.

**Comment by afridi26** [comment]
I have tested this locally and the same behaviour is on https://webauthn.io/. Need to deploy fresh version :) thanks

**Comment by eigenl** [comment]
Not sure if this is related, but when registering the same username multiple times and then trying to log in, the RP sends multiple **authenticatorGetAssertion** calls with a single credential in _ allowList_ rather than all credentials like the spec says. For example this happens when you respond with CTAP2_ERR_CREDENTIAL_EXCLUDED for the first credential.

Looking at the browser console, I see the public keys in a single array, but the authenticator only receives one at a time.

**Comment by m9a** [comment]
Hi @aseigler, do you know if this issue fixed in master? I just observed a similar error with double registration on top of tree master and wondering if it's the same bug. As I see the fido-testing fix has not yet been merged into master.

**Comment by aseigler** [comment]
> Hi @aseigler @nicksteele, do you know if this issue fixed in master? I just observed a similar error with double registration on top of tree master and wondering if it's the same bug. As I see the fido-testing fix has not yet been merged into master.

As far as I know, it is not fixed in master.

**Comment by MasterKale** [comment]
I believe this is fixed in the latest "v2" version of this site. I'm getting told by Chrome when I've tried re-registering something at least:

![Screen Shot 2022-09-26 at 1 37 25 PM](https://user-images.githubusercontent.com/5166470/192375276-e1f1b87b-2cb6-4da9-991c-1c87bbd390a2.png)

(Weird that it says "security key" when I tried to enroll the platform authenticator, but that's a Chrome problem)
