### ISSUE TITLE
UserVerfication setting does not have any effect

### ISSUE THREAD

**Issue by Sebi2020** [duo-labs/webauthn.io#48]
Related issues: #13 (marked as fixed, but it isn't)

I think there must be some implementation error on webauthn.io regarding user verfication, because it's impossible to do logins without PIN input prompts.

For reference try they same on [https://webauthntest.azurewebsites.net/login.html](https://webauthntest.azurewebsites.net/login.html) (choose a user name first).
It works as expected on this test site, but fails on webauthn.io

## Environment
**OS**: Windows 10
**Browser**: Chrome or Firefox
**Security Key**: Yubikey 5

## Reproduction
1. Go to [webauthn.io](https://webauthn.io)
2. Choose a user name
3. Open Advanced options
4. Set _User Verfication_ to _Discouraged_ and _Register with Resident Key_ to _Required_
5. Click Register, enter PIN, etc..
6. Click Login
7. PIN dialog appears, even if you have set _User Verification_ to _Discouraged_

**Comment by MasterKale** [comment]
Fixed in the latest revamp of the site (#58)

**Comment by WinstonChenn** [comment]
Is the revamped code updated on webauthn.io site? because I don't see the "Only Registered Authenticators" option on the site. Just want to clarify.

**Comment by MasterKale** [comment]
> @MasterKale Is the revamped code updated on [webauthn.io](https://webauthn.io/) site? because I don't see the "Only Registered Authenticators" option on the site, which is shown in the example screenshot in the PR you linked to. Just want to clarify.

The option was removed [here](https://github.com/duo-labs/webauthn.io/commit/c63374c5cd0670db407f17cfc8040eb960e163ae) because it was superfluous in the face of authentication behavior that already includes all registered authenticators if you provide a username.

If you don't provide a username then you can select a credential to present to the site, so you can test usernameless/passkeys support (like what happens with conditional UI.)

**Comment by WinstonChenn** [comment]
@MasterKale Got it, thank you!
